### PR TITLE
Preparation for beta testing

### PR DESCRIPTION
**Pull request by martin-key**
I have tested a pool machine in order to check the UI. It has some really cool look and will be interesting to see how miners interact with it. However there is a lot of work needed to finish it.

- I have removed 2 items from side menu. There is no data in the API of mining core for them, so they will not be needed for now. 
- Also fixed the endpoints, they are with slightly different URL than the one listed in mining core readme
- Made some changes on worker screen. Now the data is shown correctly. 

This weekend I will add beta for mining multitool to check the work of the client.

### CODE REVIEW

**Comment by calvintam236** [comment]
@StarbuckBG can you use `<!--` and `-->` in a new line at the beginning and the end of the comment area instead adding them on every line? and please merge with latest commit I made few hours ago (looks like some changes will conflict)?

**Comment by martin-key** [comment]
About the , I suck in UI web stuff... Thanks for advice, I will do it that way.

I will merge tomorrow, it is 4 AM here and I need to get some rest. I will give you URL for server to check changes and watch for bugs.

**Comment by calvintam236** [comment]
@StarbuckBG Take care. No rush. Looking forward for the URL.

**Comment by martin-key** [comment]
Hey, @calvintam236 !
Please check. I have resolved the conflicts.

**Comment by calvintam236** [comment]
@StarbuckBG There are still conflicts.. I don't see any fixes of the `<!--` and `-->` tag. Maybe you should wait for the next few days (after @oliverw pushed all the changes for the API and my changes).

**Comment by martin-key** [comment]
Hey! Please check again. Conflicts resolved.

**Comment by calvintam236** [comment]
Hi @StarbuckBG, I still see some `<!--` tags not fixed (e.g. `connect.html`). I would suggest to put `<!--` and `-->` in new line for themselves, and please do not remove the spaces it had on some of the lines?

**Comment by calvintam236** [comment]
I think you are using the old API response for https://github.com/calvintam236/miningcore-ui/pull/11/files#diff-e6a2997a9b7c9c7c67a114b467740533L227, and I don't think it is correct.

**Comment by martin-key** [comment]
new.pool.gold is using this at the moment.

**Comment by calvintam236** [comment]
@StarbuckBG your pool and UI are outdated; hence, the chart is not loading for ETC, ZCL..

**Pull request closed without merging**
